---
# tasks file for prometheus-postgres

- name: prometheus postgres | create directories
  become: true
  file:
    path: "{{ item }}"
    recurse: true
    state: directory
  with_items:
    - /etc/postgres_exporter

- name: prometheus postgres | download
  become: true
  get_url:
    url: "https://github.com/wrouesnel/postgres_exporter/releases/download/\
      v{{ prometheus_postgres_version }}/\
      postgres_exporter_v{{ prometheus_postgres_version }}_linux-amd64.tar.gz"
    checksum: sha256:{{ prometheus_postgres_sha256 }}
    dest: "/tmp/postgres_exporter_v{{ prometheus_postgres_version }}_linux-amd64.tar.gz"

- name: prometheus postgres | install postgres-exporter
  become: true
  unarchive:
    src: "/tmp/postgres_exporter_v{{ prometheus_postgres_version }}_linux-amd64.tar.gz"
    dest: /tmp/postgres_exporter
    group: root
    owner: root
    remote_src: true

- name: prometheus postgres | symlink postgres-exporter
  become: true
  file:
    src: "/tmp/postgres_exporter/postgres_exporter"
    path: "{{ prometheus_postgres_binary_install_dir }}"
    force: true
    state: present
  notify:
    - restart prometheus-postgres

- name: prometheus postgres | configuration file
  become: true
  assemble:
    dest: /etc/postgres_exporter/postgres-queries.yml
    regexp: "^{{ prometheus_postgres_query_filenames | join('|') }}$"
    remote_src: false
    src: "{{ prometheus_postgres_query_directory }}"
  notify:
    - restart prometheus-postgres

- name: prometheus postgres | server systemd service
  become: true
  template:
    dest: /etc/systemd/system/postgres_exporter.service
    src: postgres_exporter-service.j2
  notify:
    - restart prometheus-postgres

- name: prometheus postgres | enable and start server systemd
  become: true
  systemd:
    daemon_reload: true
    enabled: true
    name: postgres_exporter.service
    state: started
